# Generated by Django 3.2.23 on 2024-05-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='students/image/')),
                ('date_of_join', models.DateField(auto_now_add=True)),
                ('parent_name', models.CharField(max_length=500)),
                ('classes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.classes', verbose_name='Classes')),
            ],
        ),
    ]
