# Generated by Django 3.2.23 on 2024-05-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('analytics_ID', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=100)),
                ('date_Generated', models.DateTimeField(auto_now_add=True)),
                ('metrics', models.TextField()),
                ('teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
    ]
