# Generated by Django 4.2.7 on 2024-05-12 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('drade_ID', models.AutoField(primary_key=True, serialize=False)),
                ('grade_Name', models.CharField(max_length=100)),
                ('grade_Point', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
