# Generated by Django 5.0.6 on 2024-05-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Name',
            new_name='Title',
        ),
    ]
